### ISSUE TITLE
How about SwiftUI ?

### ISSUE THREAD

**Issue by caramdache** [andrewcbancroft/BlogIdeaList#1]
Great post and code, thanks! It would be neat to have a version with SwiftUI. I'd love to see how both integrate.

**Comment by andrewcbancroft** [comment]
I chose to create another repo to cover SwiftUI.

Check out https://www.andrewcbancroft.com/blog/ios-development/data-persistence/using-core-data-with-swiftui-introduction/ for the blog and https://github.com/andrewcbancroft/BlogIdeaList-SwiftUI/ for the repo!  🙌🏻
